FWPNMAKE.FRM
C:\WINDOWS\SYSTEM\CMDIALOG.VBX
WPN.BAS
CALCMP2.BAS
MOVESWPN.BAS
ROT13.BAS
FMOVEWPN.FRM
ProjWinSize=17,532,266,208
ProjWinShow=2
IconForm="fWpnMake"
Title="ChUB 2000 Weapon Editor"
ExeName="WPNEDIT.EXE"
