FMVEDIT.FRM
C:\WINDOWS\SYSTEM\CMDIALOG.VBX
CALCMP.BAS
MV1.BAS
MOVESAVE.BAS
ROT13.BAS
ProjWinSize=34,517,252,221
ProjWinShow=2
IconForm="fMoveEdit"
Title="ChUB 2000 Move Editor"
ExeName="MOVEDIT.EXE"
